# 1. Numpy `axis`

*[CEGM1000 MUDE](http://mude.citg.tudelft.nl/)*

*Written by: Robert Lanzafame*

*Due: Friday, December 5, 2025.*

In [1]:
import numpy as np
import matplotlib.pyplot as plt

Often when we have a long sequence of data we would like to evaluate specific sub-sets of it. For example, if we have 10 years worth of hourly measurements, but would like to evaluate the monthly or weekly characteristics. Often we can store our data in a structured way and then use some indexing capabilities of Numpy to evaluate it in a smart way. Check out the following simple tips, then try and apply it in practice.

<div style="background-color:#AABAB2; color: black; width:90%; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>

$\text{Task 1.1:}$
    
Read and run the cells below, making sure you understand what is happening (i.e., completing evaluations on the rows and columns of the matrix).
</p>
</div>


First, let's start by collecting a "long" sequence of data.

In [2]:
A = np.array([1, 20, 300, 1, 2, 3])
print(A)

[  1  20 300   1   2   3]



It is easy to restructure it into a matrix form; in this case, 2 rows and 3 columns.

In [3]:
B = np.reshape(A, (2, 3))
print(B)

[[  1  20 300]
 [  1   2   3]]



In Numpy, "axes" are used to specify the structure of an array using the `axis` keyword argument. For this assignment, we are particularly interested in performing operations along the 0th and 1st axes of the array, which correspond to the columns and rows, respectively. Check it out:

In [4]:
B.mean(axis=0)

array([  1. ,  11. , 151.5])


Looking along the other axis:

In [5]:
B.mean(axis=1)

array([107.,   2.])


And you can do it for other methods too!

In [6]:
B.std(axis=1)

array([136.6918676 ,   0.81649658])

<div style="background-color:#AABAB2; color: black; width:90%; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>

$\text{Task 1.2:}$
    
Read the simple story below and use the tips described above to complete the partially completed code cell.
</p>
</div>


Suppose you and a group of friends would like to evaluate your financial decisions, and you decide to review how many coins you spend at PSOR, the CEG student pub, to practice your Python skills. You have assembled data on the number of coins purchased per month, for several years, starting from when you first met in September, through August, 3 years later.

In [7]:
coins = [46, 28, 16, 27,
         22, 24, 31, 12,
         32, 36, 12, 0,
         41, 27, 21, 26,
         21, 19, 18, 35,
         14, 34, 8, 0,
         53, 34, 23, 35,
         28, 26, 18, 13,
         12, 14, 34, 0]

coins_matrix = np.reshape(coins, (3, 12))
print(coins_matrix)

[[46 28 16 27 22 24 31 12 32 36 12  0]
 [41 27 21 26 21 19 18 35 14 34  8  0]
 [53 34 23 35 28 26 18 13 12 14 34  0]]


In [ ]:
np.set_printoptions(precision=1)

average_monthly_coins = 
average_monthly_coins_per_month = 
average_coins_september = 
average_coins_january = 
max_coins_month = 
max_coins_year =

print(f'The average number of coins spent per month is: {average_monthly_coins:.1f}')
print('The average number of coins spent per month for each year is:', average_monthly_coins_per_month)
print(f'The average number of coins spent each september: {average_coins_september:.1f}')
print(f'The average number of coins spent each january: {average_coins_january:.1f}')
print(f'Max coins spent in any month: {max_coins_month:.1f}')
print(f'Max coins spent in any year: {max_coins_year:.1f}')

In [ ]:
np.set_printoptions(precision=1)

average_monthly_coins = np.mean(coins)
average_monthly_coins_per_month = coins_matrix.mean(axis=1)
average_coins_september = coins_matrix.mean(axis=0)[0]
average_coins_january = coins_matrix.mean(axis=0)[4]
max_coins_month = max(coins_matrix.max(axis=0))
max_coins_year = max(coins_matrix.sum(axis=1))

print(f'The average number of coins spent per month is: {average_monthly_coins:.1f}')
print('The average number of coins spent per month for each year is:', average_monthly_coins_per_month)
print(f'The average number of coins spent each september: {average_coins_september:.1f}')
print(f'The average number of coins spent each january: {average_coins_january:.1f}')
print(f'Max coins spent in any month: {max_coins_month:.1f}')
print(f'Max coins spent in any year: {max_coins_year:.1f}')

The average number of coins spent per month is: 23.3
The average number of coins spent per month for each year is: [23.8 22.  24.2]
The average number of coins spent each september: 46.7
The average number of coins spent each january: 23.7
Max coins spent in any month: 53.0
Max coins spent in any year: 290.0


<div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc;">
  <div style="display: flex; justify-content: flex-end; gap: 20px; align-items: center;">
    <a rel="MUDE" href="http://mude.citg.tudelft.nl/">
      <img alt="MUDE" style="width:100px; height:auto;" src="https://gitlab.tudelft.nl/mude/public/-/raw/main/mude-logo/MUDE_Logo-small.png" />
    </a>
    <a rel="TU Delft" href="https://www.tudelft.nl/en/ceg">
      <img alt="TU Delft" style="width:100px; height:auto;" src="https://gitlab.tudelft.nl/mude/public/-/raw/main/tu-logo/TU_P1_full-color.png" />
    </a>
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
      <img alt="Creative Commons License" style="width:88px; height:auto;" src="https://i.creativecommons.org/l/by/4.0/88x31.png" />
    </a>
  </div>
  <div style="font-size: 75%; margin-top: 10px; text-align: right;">
    &copy; Copyright 2025 <a rel="MUDE" href="http://mude.citg.tudelft.nl/">MUDE</a> TU Delft. 
    This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">CC BY 4.0 License</a>.
  </div>
</div>